[package]
name = "backend"
version = "0.1.0"
edition = "2021"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
can-dbc="5.0.0"
bitreader = "0.3.6"